### PR TITLE
fix #842 #837

### LINKED ISSUE #842: Bug/metabase
**Describe the bug**

when doing 
``` 
sudo cscli dashboard setup --listen 0.0.0.0
? For metabase docker to be able to access SQLite file we need to add a new group called 'crowdsec' to the system, is it ok for you ? Yes
INFO[01-07-2021 10:12:53 AM] Pulling docker image metabase/metabase:v0.37.0.2 
FATA[01-07-2021 10:12:53 AM] container create: failed to pull docker image : Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? 
```
**To Reproduce**
1. trying to install dashboard without docker

**Expected behavior**
The whole metabase stuff is bound to fail, but a crowdsec group is added. The system shouldn't be modified, if the stuff is bound to fail.

What I suggest is to do things otherwise, begin by checking that docker is available, and then modify the system to fit in.

### PR DESCRIPTION
**Pull request by buixor**
This PR fixes #842 and #837

### CODE REVIEW

File: cmd/crowdsec-cli/dashboard.go [hunk 1]
```diff
@@ -72,7 +67,9 @@ cscli dashboard remove
 				log.Errorf("This command requires direct database access (must be run on the local API machine)")
 				log.Fatalf(err.Error())
 			}
-
+			if err := metabase.TestAvailability(); err != nil {
```
Comment (blotus) [inline cmd/crowdsec-cli/dashboard.go:70]: Move this check in first.
Absence of docker / arch != amd64 are 'bigger' issues (or at least harder to fix) than having LAPI disabled.

File: cmd/crowdsec-cli/dashboard.go [hunk 2]
```diff
@@ -73,6 +71,12 @@ cscli dashboard remove
 				log.Fatalf(err.Error())
 			}
 
+			if !metabase.IsContainerExist(metabaseContainerID) {
```
Comment (buixor) [inline cmd/crowdsec-cli/dashboard.go:74]: please a tiny comz here, we're going to forget about it very quickly :p

**Review by AlteredCoder — APPROVED** [review]
