### PR TITLE
Fix REQUEST_URI behavior + fix #2891

### LINKED ISSUE #2891: [AppSec] ParsedRequest.URL is the request sent to appsec endpoint
When we parse the request to a struct we provide `url` the parameter of `r.URL` which is the original request sent to appsec endpoint we should in fact use the parsed url

### PR DESCRIPTION
**Pull request by buixor**
- [x] Checked that it doesn't break existing vpatch rules (`cscli hubtest run --appsec --all`)
 - [x] Add the new helpers in the doc (`normalizepath`, `trim`, `urldecode`, `htmlentitydecode`)
 - [x] Fix some documentation (`contain` -> `contains`. Remove `hexdecode` that doesn't exist)

### CODE REVIEW

File: pkg/appsec/request.go [hunk 1]
```diff
@@ -30,6 +30,7 @@ type ParsedRequest struct {
 	Host                 string                  `json:"host,omitempty"`
 	ClientIP             string                  `json:"client_ip,omitempty"`
 	URI                  string                  `json:"uri,omitempty"`
+	Path                 string                  `json:"path,omitempty"`
```
Comment (buixor) [inline pkg/appsec/request.go:33]: drop this

**Review by LaurenceJJones — APPROVED** [review]
LGTM tested with a basic remote http includes and it seems to be working now
