### PR TITLE
Parser visit split

### LINKED ISSUE #1118: Bug/cscli: fragile collection dependencies
**Describe the bug**

If two collections have common elements, uninstalling one collection taints the other.

**To Reproduce**

Note: The `crowdsecurity/freebsd` and `crowdsecurity/linux` collections have, today, the exact same elements, one of which is the `crowdsecurity/sshd` collection.

```
# cscli collections list
--------------------------------------------------------------------------------
 NAME                 📦 STATUS   VERSION  LOCAL PATH                           
--------------------------------------------------------------------------------
 crowdsecurity/sshd   ✔️  enabled  0.2      /etc/crowdsec/collections/sshd.yaml  
 crowdsecurity/linux  ✔️  enabled  0.2      /etc/crowdsec/collections/linux.yaml 
--------------------------------------------------------------------------------
# cscli install crowdsecurity/freebsd
[...]
# cscli collections list
[...]
 crowdsecurity/sshd   ✔️  enabled  0.2      /etc/crowdsec/collections/sshd.yaml  
 crowdsecurity/freebsd  ✔️  enabled  0.1      /etc/crowdsec/collections/freebsd.yaml 
 crowdsecurity/linux  ✔️  enabled  0.2      /etc/crowdsec/collections/linux.yaml 
# cscli collections remove crowdsecurity/freebsd
[...]
# cscli collections list
----------------------------------------------------------------------------------------
 NAME                 📦 STATUS           VERSION  LOCAL PATH                           
----------------------------------------------------------------------------------------
 crowdsecurity/linux  ⚠️  enabled,tainted  0.2      /etc/crowdsec/collections/linux.yaml 

```

Reinstalling `crowdsecurity/linux` removes the taint (and reinstalls `crowdsecurity/sshd`) although the command shows a fatal error (_error while enabling  crowdsecurity/linux : crowdsecurity/linux is tainted, won't enable unless --force_).

**Expected behavior**

Installing and immediately uninstalling any collection should not impact other objects. Removing `crowdsecurity/freebsd` should not automatically remove `crowdsecurity/sshd` if the latter was installed by hand or by another collection.
At least, reinstalling the tainted collection should not return the message "error... won't enable unless --force" because the collections is correctly installed, untainted and enabled.

### PR DESCRIPTION
**Pull request by buixor**
- break the parser_visit function
 - fix #1118

### CODE REVIEW

File: pkg/cwhub/loader.go [hunk 1]
```diff
@@ -20,253 +19,303 @@ import (
...
+	if discard {
+		return nil
+	}
+
+	path_components := strings.Split(path, string(filepath.Separator))
+
+	if len(path_components) < 2 {
+		log.Fatalf("path is too short : %s (%d)", path, len(path_components))
+	}
+	log.Tracef("in data dir")
```
Comment (AlteredCoder) [inline pkg/cwhub/loader.go]: i think this tracef is useless

**Review by AlteredCoder — APPROVED** [review]
